### PR TITLE
adds custom didToggle method

### PR DESCRIPTION
**Pull request by jbailey4**
Closes https://github.com/tedconf/ember-collapsible-panel/issues/5

### CODE REVIEW

**Comment by samselikoff** [comment]
Looks great! Any chance you could add a test for this?

**Comment by jbailey4** [comment]
Sorry for the late response. Yep, I'll get a test in for this, thanks!

**Comment by jbailey4** [comment]
@samselikoff Added a new test for this feature, ready for another review.

**Comment by samselikoff** [comment]
Thank you! Published in https://github.com/tedconf/ember-collapsible-panel/releases/tag/v3.1.1

**Pull request merged**
