### PR TITLE
Fix typo in cp-panel

### PR DESCRIPTION
**Pull request by el1t**
Change `nane` -> `name`

### CODE REVIEW

**Comment by samselikoff** [comment]
@brenna could I have commit access?

**Comment by brenna** [comment]
added @samselikoff!

**Comment by samselikoff** [comment]
still says I don't have write access

**Comment by CpuID** [comment]
In the GH UI:

Sam Selikoff
Awaiting samselikoff's response

**Comment by brenna** [comment]
@samselikoff It says waiting for you to accept your invite for write access. I'll re-send.

**Comment by samselikoff** [comment]
👍  such a subtle alert. thanks yall!

**Comment by samselikoff** [comment]
thanks @el1t

**Pull request merged**
