### PR TITLE
Panel states

### PR DESCRIPTION
**Pull request by ryanto**
This PR introduces the concept of panelActions, an API that allows you to programmatically do things like open all panels in a group.

See this test: https://github.com/tedconf/ember-collapsible-panel/blob/panel_state/tests/integration/cp-panels-test.js#L43-L66

Also, all state for panels is stored outside of the component classes. This means that all panels survive rerenders allowing a user to open a panel, navigate to another page, navigate back, and the panel will remain open.

All tests are green. We could probably use a few more tests, but this is a good start.

Before this gets merged I'd like to see how this interacts on the gh-pages examples, those demos are always good final tests. What's the best way for me to generate/test there?

cc @samselikoff @brenna

### CODE REVIEW

**Comment by samselikoff** [comment]
you can run `ember s` from the addon and visit `localhost:4200` to view the dummy app

**Comment by brenna** [comment]
I can add an example to the docs and test this out if you can give me a quick summary of the API.

**Comment by samselikoff** [comment]
Another use case for programmatic control (I need this in an app I'm working on):

``` hbs
{{#cp-panel}}
  {{#cp-panel-toggle class='Reminder-list-item__toggle'}}
    {{reminder.action}}
    <p class='Reminder-list-item__summary'>
      <small>Every {{reminder.shorthand}}</small>
    </p>
  {{/cp-panel-toggle}}
  {{#cp-panel-body class='Reminder-list-item__body'}}

    {{reminders/lib/edit-reminder-form reminder=reminder willDelete='toggleWillDelete' didSave='closePanel'}}

  {{/cp-panel-body}}
{{/cp-panel}}

{{#if willDelete}}
  {{reminders/lib/delete-reminder reminder=reminder dismiss='toggleWillDelete'}}
{{/if}}
```

I want the panel to close when `{{edit-reminder-form}}` successfully saves

**Comment by samselikoff** [comment]
Actually if I used this branch can I bind my `{{cp-panel is-open=isOpen}}`? In master right now, `open=` binding only affects the initial render

**Comment by samselikoff** [comment]
status on this? can I help?

**Comment by ryanto** [comment]
Needs travis attention: https://travis-ci.org/tedconf/ember-collapsible-panel/jobs/79923912

**Comment by samselikoff** [comment]
:tada:

**Pull request merged**
