### PR TITLE
added isOpen

### PR DESCRIPTION
**Pull request by ghost**
solves #28. thanks @samselikoff!

### CODE REVIEW

**Comment by samselikoff** [comment]
Awesomeness, thanks! Could we leave he package.jsom version, typically we don't bump until we are ready to tag in a separate commit.

**Comment by samselikoff** [comment]
🙌

**Comment by daniel-de-wit** [comment]
When is a new version released exposing this feature?

**Comment by jbailey4** [comment]
@samselikoff Can we cut a new release with this api? Needing to add some `aria` props depending on `isOpen` state for accessibility. 

Any work needed to get a new release out, glad to help. 😄 

And nice work @shicholas getting this PR in!

**Comment by samselikoff** [comment]
@daniel-de-wit @jbailey4 published: https://github.com/tedconf/ember-collapsible-panel/releases/tag/v2.1.0

**Pull request merged**
